config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'pages#about'
  get 'projects', to: 'pages#projects'
  get 'resume', to: 'pages#resume'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'pages/download_image', to: 'pages#download_image', as: "download_image"

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def projects
  end

  def resume
  end

  def download_image
    # Define the path to your image file
    image_path = Rails.root.join('app', 'assets', 'images', 'resume.png')

    # Set the filename for the downloaded file
    filename = 'recce_cristea_resume.png'

    # Send the file as an attachment
    send_file(image_path, filename: filename, disposition: 'attachment')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div id="footer" class="bg-dark text-light">
    <div class="row" style="width:100%">
        <div class="col ms-2 mt-4">
            <a href="https://www.linkedin.com/in/reece-cristea/" target="_blank"><%= image_tag('linkedin2.png')%></a>
            <a href="https://github.com/reece-cristea/" target="_blank"><%= image_tag('github.png')%></a>
        </div>
        <div class="col text-end me-2">
            <p class="fs-4 mb-0">Contact Me</p>
            <a class="text-light mb-0" href="mailto: rcinlae36@gmail.com">
                rcinlae36@gmail.com
            </a>
            <p class="mb-0">+1(805)915-9606</p>
        </div>
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-light fs-3" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-light fs-3" href="/about">About Me</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-light fs-3" aria-current="page" href="/projects">Projects</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-light fs-3" aria-current="page" href="/resume">Resume</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,1,0"/>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <div class="bg-light" style="height:auto;width:auto;">
        <%= render 'layouts/navbar'%>
        <%= yield %>
        <%= render 'layouts/footer'%>
      </div>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-body my-5 fade-in">
    <section class="banner my-5">
        <%= image_tag('reece.jpg', class: "rounded-3 shadow-lg banner-img", alt: "Reece Cristea")%>
        <div class="banner-content">
            <h2>Hi, I'm Reece!</h2>
            <p style="max-width: 780px;">
                I am an entry level software engineer/developer looking to get some hands-on experience in the field. 
                I specialize in front end application development, but I welcome all challenges that any project will pose.
            </p>
            <div class="accordion mt-3" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Education
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            I graduated from <i>Champlain College</i> in Burlington, Vermont with a <strong> major in Computer Science and Innovation and a minor in Mathematics</strong>.
                            My cirriculum had me learning the foundations of programming from the very first semester and continued to advance my knowledge and skills to the point where
                            I was able to build my own application or website for any platform at the end of my senior year. Although I don't know everything there is to know about proramming,
                            my time at school taught me so much on what it means to develop software. Below are some of the more notable courses I completed while at Champlain College:
                        </div>
                        <div class="row mx-3 mb-3">
                            <div class="col text-start">
                                <li><em>Intro to Mobile and Web Development</em></li>
                                <li><em>Data Structures and Algorithms</em></li>
                                <li><em>Open Source Software Development</em></li>
                                <li><em>Network Programming</em></li>
                                <li><em>Database Management and Systems</em></li>
                                <li><em>Linux/Unix Programming</em></li>
                            </div>
                            <div class="col text-start">
                                <li><em>Computer Architecture</em></li>
                                <li><em>Android Development</em></li>
                                <li><em>Advanced Programming</em></li>
                                <li><em>Emerging Programming Languages</em></li>
                                <li><em>Software Refactoring</em></li>
                                <li><em>Vector Calculus</em></li>
                                <li><em>Matrices, Vectors, and 3D Math</em></li>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            Technologies
                        </button>
                    </h2>
                    <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                        <div class="accordion-body" style="display: table;">
                            During all of my schooling and across all of my projects I have completed, I have learned about and used a multitude of various different programming 
                            languages and tools. I'm not really an expert in any of them, but I do have a very good understanding of most of them and I'm able to use them in a 
                            professional setting. I can also adapt super quickly to any programming language and be able to use it well within a few weeks because I have learned 
                            about the different programming language paradigms and their characteristics. That being said, below are a list of technologies I'm comfortable with:
                        </div>
                        <div class="row mx-3 mb-3">
                            <div class="col text-start">
                                <li><em>HTML5</em></li>
                                <li><em>CSS3</em></li>
                                <li><em>JavaScript</em></li>
                                <li><em>Bootstrap</em></li>
                                <li><em>Ruby On Rails</em></li>
                                <li><em>SQL</em></li>
                            </div>
                            <div class="col text-start">
                                <li><em>C#</em></li>
                                <li><em>C++</em></li>
                                <li><em>Python</em></li>
                                <li><em>Java</em></li>
                                <li><em>Dart</em></li>
                                <li><em>Flutter SDK</em></li>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            Hobbies
                        </button>
                    </h2>
                    <div id="collapseThree" class="accordion-collapse collapse " data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            Some of my interests, aside from computer science, include video games, cars, Japanese culture, working out, and music. During my time in college, I played 
                            for three different varsity esports teams (Overwatch, Valorant, and Rocket League). This experience provided me with a deep understanding of teamwork and 
                            emphasized the crucial role of communication in achieving success. Additionally, I have been casually studying Japanese for a year now and can engage in 
                            conversations on basic topics. Music plays a significant role in my life, and I enjoy listening to it during various activities such as working out, 
                            playing games, working on projects, driving, and even while sleeping at times. My favorite genres would probably be EDM, Japanese Rock, Lofi, and Indie Pop. 
                            Looking ahead, my ultimate career goal is to work as a front-end web developer. I really enjoy the different aspects and challenges web development has to offer
                            and my aim as a web developer would be to make the online experience as simple and as pleasant as it can be for users who don't really have a lot of technical experience.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div style="height:200px">
    </div>
</div>

app/views/pages/home.html.erb
<div class="text-center display-1 text-dark my-5">
    Welcome!
</div>
<div class="row ps-5 gx-5 gx-md-5 mb-5 align-items-center text-center" style="width:100%">
    <div class="col-12 col-md-6 ps-4">
        <div class="display-3 text-center">
            Check out some of my other pages to learn more about me and feel
            free to contact me with any questions you have.
        </div>
    </div>
    <div class="col-12 col-md-6 text-center ps-4">
        <div class="slideshow" style="max-width: 100%; overflow: hidden; display: inline-block;">
            <div name="mySlides">
                <div class="border rounded border-4 border-dark">
                    <div name="slideImg" class="ss-fade-in">
                        <%= image_tag('champ3.png', style: "height:auto;width:100%;")%>
                    </div>
                </div>
            </div>
            <div name="mySlides" class="invis">
                <div class="border rounded border-4 border-dark">
                    <div name="slideImg" class="ss-fade-in">
                        <%= image_tag('wordcloud.jpg', style: "height:auto;width:100%;")%>
                    </div>
                </div>
            </div>
            <div name="mySlides" class="invis">
                <div class="border rounded border-4 border-dark">
                    <div name="slideImg" class="ss-fade-in">
                        <%= image_tag('cce.png', style: "height:auto;width:100%;")%>
                    </div>
                </div>
            </div>
            <div name="mySlides" class="invis">
                <div class="border rounded border-4 border-dark">
                    <div name="slideImg" class="ss-fade-in">
                        <%= image_tag('champlain01.jpg', style: "height:auto;width:100%;")%>
                    </div>
                </div>
            </div>
            <div name="mySlides" class="invis">
                <div class="border rounded border-4 border-dark">
                    <div name="slideImg" class="ss-fade-in">
                        <%= image_tag('japan.jpg', style: "height:auto;width:100%;")%>
                    </div>
                </div>
            </div>
            <div name="mySlides" class="invis">
                <div class="border rounded border-4 border-dark">
                    <div name="slideImg" class="ss-fade-in">
                        <%= image_tag('champlain02.jpg', style: "height:auto;width:100%;")%>
                    </div>
                </div>
            </div>
            <div name="mySlides" class="text-center invis">
                <div class="border rounded border-4 border-dark">
                    <div name="slideImg" class="ss-fade-in">
                        <%= image_tag('spotify.png', style: "height:auto;width:100%;")%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    window.onload = function () {
        showSlides(0);
    };

    function showSlides(index) {
        let slideIndex = index;
        let i;
        let slides = document.getElementsByName("mySlides");
        let slideImgs = document.getElementsByName("slideImg");
        for (i = 0; i < slides.length; i++) {
            slides[i].className = "invis";
            slideImgs[i].className = "ss-fade-in";
        }
        slideIndex++;
        if (slideIndex > slides.length) {
            slideIndex = 1;
        }
        slides[slideIndex - 1].className = "";

        setTimeout(function () {
            setFadeOut(slideIndex);
        }, 4000);
    }

    function setFadeOut(index) {
        let slideIndex = index;
        let j;
        let slideImgs = document.getElementsByName("slideImg");
        for (j = 0; j < slideImgs.length; j++) {
            slideImgs[j].className = "ss-fade-out";
        }
        if (slideImgs.length == 0) {
            waitForHomePage(slideIndex);
        } else {
            setTimeout(function () {
                showSlides(slideIndex);
            }, 750);
        }
    }
    function waitForHomePage(index) {
        let slideIndex = index;
        let slideImgs = document.getElementsByName("slideImg");
        if (slideImgs.length == 0) {
            setTimeout(function () {
                waitForHomePage(slideIndex);
            }, 4000);
        } else {
            setFadeOut(slideIndex);
        }
    }

</script>

app/views/pages/projects.html.erb
<div class="container text-dark text-center fade-in">
    <p class="display-3 mt-5">Here are some of the projects I have worked on.</h1>
    <div class="card-list">
        <div class="project-card">
            <%= image_tag('chess.PNG', class: "project-card-img", alt: "Chess")%>
            <div>
                <h1 class="text-light">
                Chess
                </h1>
                <p class="text-light">
                    I love to play Chess (even though I'm not very good at it) so this project was perfect for me to put my HTML and JavaScript skills to the test.
                    This is an offline, in browser version of Chess I have created, using Bitboards as the game's main board. If you are unfamiliar with Bitboards, 
                    they are essentially a way to store the state of any game board using bits in a large number. This makes the game extremly efficient by holding
                    current available moves and the state of the board as numbers instead of as arrays of objects. I'm still working on this project and plan to have 
                    it as its own website in the near future.
                </p>
                <a href="https://github.com/reece-cristea/chess" target="_blank" class="project-card-button">Github</a>
            </div>
        </div>
        <div class="project-card">
            <%= image_tag('napos.png', class: "project-card-img", alt: "NAPOS")%>
            <div>
                <h1 class="text-light">
                NAPOS POS
                </h1>
                <p class="text-light">
                    This project was my senior capstone project for 2022 and 2023 and we used the technologies: Dart and the Flutter framework, MySql, Golang, Nodejs, and the Square SDK. 
                    It is a Point of Sales Android application designed for use by small restaurants. The interface is simple, intuitive, and easy to learn and use. Most restaurant Point 
                    of Sales systmes can be expensive and complicated or frustrating for waiters/servers to use, so the goal of this project was to create a solution to that. With our app, 
                    you can take orders, make changes to any items on the menu, change the menu itself, view past orders, mark when orders are completed, and complete monetary transactions. 
                    As of right now our servers that we used to run our app are not running, but feel free to check out the GitHub to see some screenshots and look at the code.
                </p>
                <a href="https://github.com/AlecRoss01/NAPOS-POS-System" target="_blank" class="project-card-button">Github</a>
            </div>
        </div>
        <div class="project-card">
            <%= image_tag('discord.png', class: "project-card-img", alt: "Discord Bot")%>
            <div>
                <h1 class="text-light">
                Discord Bot
                </h1>
                <p class="text-light">
                    Throughout my time in college, I had used discord a lot to keep in touch with my friends back home and collaborate with other students on projects and such. 
                    During my first year, I decided to make a discord bot using Python as a fun project. At the time I had never used python so it was a great learning opportunity as well.
                    The bot is not set up on a remote server so I have to run it manually, but when it is up an running and a part of a server, it can be used to create tier lists of anything 
                    you want for your discord. Movies, games, music, characters, whatever you want, and you can use it to see everyone else's tier lists as well.
                </p>
                <a href="https://github.com/reece-cristea/tier-list-creation-discord-bot" target="_blank" class="project-card-button">Github</a>
            </div>
        </div>
        <div class="project-card">
            <%= image_tag('bj.PNG', class: "project-card-img", alt: "Chess")%>
            <div>
                <h1 class="text-light">
                Simple Black Jack
                </h1>
                <p class="text-light">
                    This is my implementation of simple black jack using Dart and the Flutter framework. The player and the dealer are each dealt one card and the player has the option of hitting or staying.
                    Once the player clicks stay the deal draws their cards until their cards sum to a total of more than 15. The winner is then calculated and the player can choose to play again.
                    The deck consists of one suit, 14 cards, but with a little more work on it, a 52 card deck could be implemented as well as some visual changes to give it a more finished look. 
                    Follow the instructions in the README if you want to play it yourself.
                </p>
                <a href="https://github.com/reece-cristea/blackjack_pres" target="_blank" class="project-card-button">Github</a>
            </div>
        </div>
    </div>
</div>

app/views/pages/resume.html.erb
<div class="py-5 ms-5 text-center" style="height: 100%">
    <div class="row w-100 justify-content-around">
        <div class="col-md-10 fade-in">
            <%= image_tag('resume.png', style: "width:100%;")%>
        </div>
        <div class="col">
            <%= link_to "Download", download_image_path, class: "btn btn-primary mt-5 fade-in text-light" %>
        </div>
    </div>
</div>